services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/nginx/Dockerfile
      target: nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    ports:
      - "${APP_WEB_PORT}:80"
    volumes:
      - ./:${APP_PATH}
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    build:
      args:
        gid: ${GID}
        uid: ${UID}
        xdebug_idekey: ${XDEBUG_IDEKEY}
        xdebug_client_port: ${XDEBUG_CLIENT_PORT}
      context: .
      dockerfile: ./docker/dockerfiles/php/Dockerfile
      target: dev
    container_name: ${COMPOSE_PROJECT_NAME}-php
    volumes:
      - ./:/var/www/app
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/config/php/supervisord-octane.conf:/etc/supervisor/conf.d/supervisord.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${APP_VITE_PORT}:5173"

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    build:
      context: .
      dockerfile: ./docker/dockerfiles/postgres/Dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/config/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/config/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "${APP_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 10s
      retries: 10

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:8.2-alpine
    volumes:
      - redis-data:/data
    ports:
      - "${APP_REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

  scheduler:
    container_name: ${COMPOSE_PROJECT_NAME}-scheduler
    build:
      args:
        gid: ${GID}
        uid: ${UID}
      context: .
      dockerfile: ./docker/dockerfiles/php/Dockerfile
      target: scheduler
    volumes:
      - ./:${APP_PATH}
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: on-failure
    depends_on:
      - php

  worker:
    container_name: ${COMPOSE_PROJECT_NAME}-worker
    build:
      args:
        gid: ${GID}
        uid: ${UID}
      context: .
      dockerfile: ./docker/dockerfiles/php/Dockerfile
      target: worker
    volumes:
      - ./:${APP_PATH}
      - ./docker/config/php/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: on-failure
    depends_on:
      - php

volumes:
  db-data:
  redis-data: